module.exports = {
  success: 'Success',
  failure: 'Failure',
  registration: 'You have registered successfully. We send a verification mail. Please verify your mail before proceeding. Thank you :-)',
  emailVerified: 'Thank you for verified thats none other. Now you can login. :-)',
  linkExpired: 'This link is expired or unauthorized',
  wrongEmail: 'Email or Password is wrong',
  loggedIn: 'LogIn Successfully',
  accountDeactivated: 'Your account is deactivated please contact admin',
  emailNotVerified: 'Please verify your email before login',
  boardCreated: 'Board created successfully',
  boardUpdated: 'Board updated successfully',
  userAlreadyInvited: 'User already invited for the board',
  userInvited: 'User invited successfully. Verification link send to user account',
  invitedRegistration: 'You have registered successfully',
  listCreated: 'List created successfully',
  listUpdated: 'List updated successfully',
  ticketCreated: 'Ticket created successfully',
  ticketUpdated: 'Ticket updated successfully',
  ticketComment: 'Comment added successfully'
};
